title: dominic_ondigo
logo: "/images/2019-05-02.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Am a self thought data science enthusiast, python programmer and a problem solver.<br>
   
  <br>Currently am undertaking data science at World Quant University whereby I enjoy Learning by analyzing insights from data.<br>
  
  
  <a href="http://www.linkedin.com/in/dominic-ondigo-81b67791/">LinkedIn</a>
  <a href="https://github.com/dominicondigo/">Github</a>
  <a href="https://twitter.com/dominicondigo/">Twitter</a>
  <a href="https://forms.gle/4Vn4SYvyS1LRtd9A8/">LET'S TALK</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-142586770-1 # your Google Analytics tracking ID here

